### ISSUE TITLE
Unnecessary message updates available

### ISSUE THREAD

**Issue by mechtester** [nomandhoni-cs/blink-eye#102]
Updated to latest version  and restarted

https://github.com/user-attachments/assets/32be35f3-7407-4f7e-8f6c-c67ce9930f00

when ever remainder alert came on right bottom corner got message as  updates available

**Comment by nomandhoni-cs** [comment]
@mechtester Just fixed this false positive in this https://github.com/nomandhoni-cs/blink-eye/pull/101

After you downloaded I have deployed a this new fix to the v2.0.0.

Can you please reinstall the app, This time it will not show any false update message.

And again man!! Thanks a lot for testing the. Literally a lifesaver
