### ISSUE TITLE
Volume seems to always restore to 10 and not the previous volume

### ISSUE THREAD

**Issue by Ceynou** [nomandhoni-cs/blink-eye#131]
What the title says, also, is it possible to not mute the volume at all?

**Comment by nomandhoni-cs** [comment]
Sorry sound mute functionality is having some issue, so we pulled that out, and working to fix that.
 
@Ceynou Did you know we are currently on `v2.4.0` of Blink Eye. With whole lot of features.
I think you are probably on `v1.4/1.5` please try out the new version. I hope you will like it.

Please go to [https://blinkeye.app/](https://blinkeye.app/) and see what are we offering now I hope you will like these new features in the meantime we fix the sound problem.

**Comment by Ceynou** [comment]
You're right I was on 1.5, thank you for the fixes !

**Comment by nomandhoni-cs** [comment]
I would highly recommend you to use the latest version from the website. We have updated our app lot. And you will get auto future update.  [https://blinkeye.app/](https://blinkeye.app/) We have added auto update functionality also to the app

You can uninstall the v1.5 and switch to the latest version.
