### ISSUE TITLE
download button doesn't work

### ISSUE THREAD

**Issue by osbyrne** [nomandhoni-cs/blink-eye#14]
Windows@latest
Chrome@latest

I go to https://blinkeye.vercel.app/
click download

nothing

**Comment by nomandhoni-cs** [comment]
@osbyrne Thanks a lot man for Immediately informing me, I am on It to solve the issue.

**Comment by nomandhoni-cs** [comment]
@osbyrne I can't thank you enough for this. Solved this issue now in https://github.com/nomandhoni-cs/blink-eye/pull/15

Now you can download properly Without any hassle
