### ISSUE TITLE
Linux version. 

### ISSUE THREAD

**Issue by fluentmoheshwar** [nomandhoni-cs/blink-eye#16]
Make a Linux executable for this program.

**Comment by nomandhoni-cs** [comment]
@fluentmoheshwar ,Currently, I don't have a linux machine. I have to try VM for Linux.
If you think you can make executable for linux. Give me a  hand, that would be so much helpful.

**Comment by fluentmoheshwar** [comment]
> @fluentmoheshwar ,Currently, I don't have a linux machine. I have to try VM for Linux.
> If you think you can make executable for linux. Give me a  hand, that would be so much helpful.

I will try when electricity comes back.

**Comment by nomandhoni-cs** [comment]
> > @fluentmoheshwar ,Currently, I don't have a linux machine. I have to try VM for Linux.
> > If you think you can make executable for linux. Give me a  hand, that would be so much helpful.
> 
> I will try when electricity comes back.

Take your time, no rush at all.

**Comment by fluentmoheshwar** [comment]
> > > @fluentmoheshwar ,Currently, I don't have a linux machine. I have to try VM for Linux.
> > > If you think you can make executable for linux. Give me a  hand, that would be so much helpful.
> > 
> > 
> > I will try when electricity comes back.
> 
> Take your time, no rush at all.

It works if I run the executable from terminal but not working when I open the executable from file explorer. But it shouldn't matter as we are going to package it anyway
