### ISSUE TITLE
Properly structure the repository for the ease of contribution

### ISSUE THREAD

**Issue by Nusab19** [nomandhoni-cs/blink-eye#22]
This same repo contains both the website and the app source code. It would be nice to have two separate repositories for that.
Now, all the source code of the app is in the root folder of the project.

But as this is a small app, making two separate folders would be enough I guess.
Then, those who want to contribute to the project can easily choose their section.

Like, I work with both Next.js and Python. But I would prefer to work with the development of the app with Python.

**Comment by nomandhoni-cs** [comment]
Sure, Could you assist me in reorganizing the repository by creating a pull request? I'd like to ensure that everything continues to work seamlessly, just as it did before, with the file paths.

**Comment by nomandhoni-cs** [comment]
Our Amazing guy organized these file in this structure, I think this resolves the problem of poorly structured project https://github.com/nomandhoni-cs/blink-eye/pull/26

**Comment by Nusab19** [comment]
Yes.

**Comment by Nusab19** [comment]
I think this issue can be closed now
