### ISSUE TITLE
Replace pip with uv

### ISSUE THREAD

**Issue by fluentmoheshwar** [nomandhoni-cs/blink-eye#35]
`uv` is an extremely fast Python package installer and resolver, written in Rust. Designed as a drop-in replacement for common `pip` and `pip-tools` workflows.

Source: https://github.com/astral-sh/uv

**Comment by Sayad-Uddin-Tahsin** [comment]
> `uv` is an extremely fast Python package installer and resolver, written in Rust. Designed as a drop-in replacement for common `pip` and `pip-tools` workflows.
> 
> Source: https://github.com/astral-sh/uv

Do `uv` has such rich library database like `pip`?

**Comment by Sayad-Uddin-Tahsin** [comment]
I don't know if we should move, seems it also depends on pip somehow. While `pip` is doing its job perfectly, why changing and reformatting the whole code (in case it changes some path thingy)?

**Comment by fluentmoheshwar** [comment]
> > `uv` is an extremely fast Python package installer and resolver, written in Rust. Designed as a drop-in replacement for common `pip` and `pip-tools` workflows.
> > Source: https://github.com/astral-sh/uv
> 
> Do `uv` has such rich library database like `pip`?

both `uv` and `pip` uses pypi and we can continue using `pip` alongside `uv` if something doesn't like `uv`

**Comment by nomandhoni-cs** [comment]
Closed this issue, Since we have migrated the app to Tauri
